
# First for the single config generator such as Ninja and Make)
macro(RedirectOutputTo dir)
    if (WIN32)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/${dir})
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/${dir})
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/${dir})
    else ()
        set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${dir})
        set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${dir})
    endif (WIN32)
endmacro(RedirectOutputTo dir)

# For multi-config generator such as MSVC and XCode
macro(RedirectMultiConfigGeneratorOutputTo dir)
    foreach (CONFIG_TYPE ${CMAKE_CONFIGURATION_TYPES})
        message(STATUS "\t\t${CONFIG_TYPE} -> build/${CONFIG_TYPE}")
        string(TOUPPER ${CONFIG_TYPE} CONFIG_TYPE)
        set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_TYPE} ${PROJECT_SOURCE_DIR}/${dir}/${CONFIG_TYPE})
        set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_TYPE} ${PROJECT_SOURCE_DIR}/${dir}/${CONFIG_TYPE})
        set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_TYPE} ${PROJECT_SOURCE_DIR}/${dir}/${CONFIG_TYPE})
    endforeach (CONFIG_TYPE ${CMAKE_CONFIGURATION_TYPES})
endmacro(RedirectMultiConfigGeneratorOutputTo dir)